#include"../Parser.h"

int get_index_from_terminal_parser(Terminals TokenKind){
    // as long as the terminals enum is in the right order, we can simply return the intefer value of that enum
    return (int)TokenKind;
}
int get_index_from_Non_terminal_parser(Non_Terminals NonTerminalKind){
    // as long as the non terminals enum is in the right order, we can simply return the intefer value of that enum
    return (int)NonTerminalKind;
}
void set_parsr_action(Parser* parser, int state, Terminals terminal, Action action){
    parser->parse_table.ActionMatrix[state][get_index_from_terminal_parser(terminal)] = action;
}
void set_parser_goto(Parser* parser, int state, Non_Terminals nonTerminal, int nextState){
    parser->parse_table.GotoMatrix[state][get_index_from_Non_terminal_parser(nonTerminal)] = nextState;
}
void init_action_table(Parser* parser){
    // iniatating the action table of the parser according the the lr shift recude automata

    int state = 0;
    state = 0;
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    state = 1;
    set_parsr_action(parser, state, DOLLAR_TOKEN, (Action){ACCEPT,-1});
    state = 2;
    set_parsr_action(parser, state, DOLLAR_TOKEN, (Action){REDUCE,1});
    state = 3;
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, DOLLAR_TOKEN, (Action){REDUCE,3});
    state = 4;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,9});
    state = 5;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,23});
    state = 6;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,24});
    state = 7;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,25});
    state = 8;
    set_parsr_action(parser, state, DOLLAR_TOKEN, (Action){REDUCE,2});
    state = 9;
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,10});
    state = 10;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,12});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    state = 11;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,15});
    state = 12;
    set_parsr_action(parser, state, OPEN_BRACE_TOKEN, (Action){SHIFT,16});
    state = 13;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,6});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){SHIFT,17});
    state = 14;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,18});
    state = 15;
    set_parsr_action(parser, state, OPEN_BRACE_TOKEN, (Action){SHIFT,19});
    state = 16;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,31});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){SHIFT,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){SHIFT,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){SHIFT,33});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){SHIFT,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 17;
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    state = 18;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,8});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,8});
    state = 19;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,31});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){SHIFT,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){SHIFT,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){SHIFT,33});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){SHIFT,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 20;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){SHIFT,53});
    state = 21;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,9});
    state = 22;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,31});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,10});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){SHIFT,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){SHIFT,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){SHIFT,33});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){SHIFT,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 23;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){SHIFT,55});
    state = 24;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){SHIFT,56});
    state = 25;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){SHIFT,57});
    state = 26;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,15});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,15});
    state = 27;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,16});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,16});
    state = 28;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){SHIFT,58});
    state = 29;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){SHIFT,59});
    state = 30;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){SHIFT,60});
    state = 31;
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,62});
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, ASSIGNMENT_TOKEN, (Action){SHIFT,61});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,60});
    state = 32;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,63});
    state = 33;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,28});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 34;
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,66});
    state = 35;
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,67});
    state = 36;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,39});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,39});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,39});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){SHIFT,68});
    state = 37;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,69});
    state = 38;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 39;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,40});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,40});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,40});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,40});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){SHIFT,71});
    state = 40;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,42});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,42});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,42});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,42});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,42});
    state = 41;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,44});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,44});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,44});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,44});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,44});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){SHIFT,72});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){SHIFT,73});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){SHIFT,74});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){SHIFT,75});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){SHIFT,76});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){SHIFT,77});
    state = 42;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,51});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){SHIFT,78});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,79});
    state = 43;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,54});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){SHIFT,80});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){SHIFT,81});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){SHIFT,82});
    state = 44;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 45;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,59});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,59});
    state = 46;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,61});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,61});
    state = 47;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 48;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 49;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,64});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,64});
    state = 50;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,65});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,65});
    state = 51;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,7});
    state = 52;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){SHIFT,86});
    state = 53;
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,5});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,5});
    set_parsr_action(parser, state, DOLLAR_TOKEN, (Action){REDUCE,5});
    state = 54;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,11});
    state = 55;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,12});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,12});
    state = 56;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,13});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,13});
    state = 57;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,14});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,14});
    state = 58;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,17});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,17});
    state = 59;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,18});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,18});
    state = 60;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,19});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,19});
    state = 61;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 62;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,89});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 63;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,22});
    state = 64;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,27});
    state = 65;
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,62});
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,60});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,60});
    state = 66;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 67;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 68;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 69;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,20});
    state = 70;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,21});
    state = 71;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 72;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 73;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 74;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 75;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 76;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 77;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 78;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 79;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 80;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 81;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 82;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 83;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,107});
    state = 84;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,62});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,62});
    state = 85;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,63});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,63});
    state = 86;
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,4});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,4});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,4});
    set_parsr_action(parser, state, DOLLAR_TOKEN, (Action){REDUCE,4});
    state = 87;
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,26});
    state = 88;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,108});
    state = 89;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,30});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,30});
    state = 90;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,31});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){SHIFT,109});
    state = 91;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,33});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,33});
    state = 92;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,110});
    state = 93;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){SHIFT,111});
    state = 94;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,41});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,41});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,41});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,41});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){SHIFT,71});
    state = 95;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,43});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,43});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,43});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,43});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,43});
    state = 96;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,45});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,45});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,45});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,45});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,45});
    state = 97;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,46});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,46});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,46});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,46});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,46});
    state = 98;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,47});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,47});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,47});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,47});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,47});
    state = 99;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,48});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,48});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,48});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,48});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,48});
    state = 100;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,49});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,49});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,49});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,49});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,49});
    state = 101;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,50});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,50});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,50});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,50});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,50});
    state = 102;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,52});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,52});
    state = 103;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,53});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,53});
    state = 104;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,55});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,55});
    state = 105;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,56});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,56});
    state = 106;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,57});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,57});
    state = 107;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,58});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,58});
    state = 108;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, COMMA_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, SEMICOLON_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, LOGICAL_OR_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, LOGICAL_AND_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, EQUAL_TO_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, NOT_EQUAL_TO_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, LESS_THEN_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, GREATER_THEN_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, LESS_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, GREATER_THEN_OR_EQUAL_TO_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, PLUS_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, MULTIPLY_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, DIVIDE_TOKEN, (Action){REDUCE,29});
    set_parsr_action(parser, state, MODULO_TOKEN, (Action){REDUCE,29});
    state = 109;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,65});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 110;
    set_parsr_action(parser, state, OPEN_BRACE_TOKEN, (Action){SHIFT,113});
    state = 111;
    set_parsr_action(parser, state, OPEN_BRACE_TOKEN, (Action){SHIFT,114});
    state = 112;
    set_parsr_action(parser, state, CLOSE_PARENTHESES_TOKEN, (Action){REDUCE,32});
    state = 113;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,31});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){SHIFT,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){SHIFT,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){SHIFT,33});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){SHIFT,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 114;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,31});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){SHIFT,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){SHIFT,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){SHIFT,33});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){SHIFT,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 115;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){SHIFT,117});
    state = 116;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){SHIFT,118});
    state = 117;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, ELSE_TOKEN, (Action){SHIFT,120});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,35});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,35});
    state = 118;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,38});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,38});
    state = 119;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,34});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,34});
    state = 120;
    set_parsr_action(parser, state, OPEN_BRACE_TOKEN, (Action){SHIFT,122});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    state = 121;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,36});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,36});
    state = 122;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){SHIFT,31});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){SHIFT,44});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){SHIFT,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){SHIFT,38});
    set_parsr_action(parser, state, INT_TOKEN, (Action){SHIFT,5});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){SHIFT,6});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){SHIFT,7});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){SHIFT,33});
    set_parsr_action(parser, state, IF_TOKEN, (Action){SHIFT,34});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){SHIFT,35});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){SHIFT,47});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){SHIFT,48});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){SHIFT,49});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){SHIFT,50});
    state = 123;
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){SHIFT,124});
    state = 124;
    set_parsr_action(parser, state, IDENTIFIER_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, OPEN_PARENTHESES_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, CLOSE_BRACE_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, GETCHAR_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, PUTCHAR_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, INT_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, CHAR_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, VOID_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, RETURN_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, IF_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, WHILE_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, MINUS_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, LOGICAL_NOT_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, DIGIT_TOKEN, (Action){REDUCE,37});
    set_parsr_action(parser, state, CHAR_LITERAL_TOKEN, (Action){REDUCE,37});

}

void init_goto_table(Parser* parser){
    int state = 0;
    state = 0;
    set_parser_goto(parser, state, NON_TERMINAL_PROGRAM, 1);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTIONS, 2);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION, 3);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 4);
    state = 1;
    state = 2;
    state = 3;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTIONS, 8);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION, 3);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 4);
    state = 4;
    state = 5;
    state = 6;
    state = 7;
    state = 8;
    state = 9;
    state = 10;
    set_parser_goto(parser, state, NON_TERMINAL_PARAMETERS, 11);
    set_parser_goto(parser, state, NON_TERMINAL_PARAMETER, 13);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 14);
    state = 11;
    state = 12;
    state = 13;
    state = 14;
    state = 15;
    state = 16;
    set_parser_goto(parser, state, NON_TERMINAL_BODY, 20);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENTS, 21);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENT, 22);
    set_parser_goto(parser, state, NON_TERMINAL_GETCHAR, 29);
    set_parser_goto(parser, state, NON_TERMINAL_PUTCHAR, 30);
    set_parser_goto(parser, state, NON_TERMINAL_DECLARATION, 24);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 32);
    set_parser_goto(parser, state, NON_TERMINAL_ASSIGNMENT, 23);
    set_parser_goto(parser, state, NON_TERMINAL_RETURN, 25);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 26);
    set_parser_goto(parser, state, NON_TERMINAL_WHILE_LOOP, 27);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 28);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 17;
    set_parser_goto(parser, state, NON_TERMINAL_PARAMETERS, 51);
    set_parser_goto(parser, state, NON_TERMINAL_PARAMETER, 13);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 14);
    state = 18;
    state = 19;
    set_parser_goto(parser, state, NON_TERMINAL_BODY, 52);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENTS, 21);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENT, 22);
    set_parser_goto(parser, state, NON_TERMINAL_GETCHAR, 29);
    set_parser_goto(parser, state, NON_TERMINAL_PUTCHAR, 30);
    set_parser_goto(parser, state, NON_TERMINAL_DECLARATION, 24);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 32);
    set_parser_goto(parser, state, NON_TERMINAL_ASSIGNMENT, 23);
    set_parser_goto(parser, state, NON_TERMINAL_RETURN, 25);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 26);
    set_parser_goto(parser, state, NON_TERMINAL_WHILE_LOOP, 27);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 28);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 20;
    state = 21;
    state = 22;
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENTS, 54);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENT, 22);
    set_parser_goto(parser, state, NON_TERMINAL_GETCHAR, 29);
    set_parser_goto(parser, state, NON_TERMINAL_PUTCHAR, 30);
    set_parser_goto(parser, state, NON_TERMINAL_DECLARATION, 24);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 32);
    set_parser_goto(parser, state, NON_TERMINAL_ASSIGNMENT, 23);
    set_parser_goto(parser, state, NON_TERMINAL_RETURN, 25);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 26);
    set_parser_goto(parser, state, NON_TERMINAL_WHILE_LOOP, 27);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 28);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 23;
    state = 24;
    state = 25;
    state = 26;
    state = 27;
    state = 28;
    state = 29;
    state = 30;
    state = 31;
    state = 32;
    state = 33;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 64);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 34;
    state = 35;
    state = 36;
    state = 37;
    state = 38;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 70);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 39;
    state = 40;
    state = 41;
    state = 42;
    state = 43;
    state = 44;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 83);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 45;
    state = 46;
    state = 47;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 84);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 48;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 85);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 49;
    state = 50;
    state = 51;
    state = 52;
    state = 53;
    state = 54;
    state = 55;
    state = 56;
    state = 57;
    state = 58;
    state = 59;
    state = 60;
    state = 61;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 87);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 62;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ARGUMENTS, 88);
    set_parser_goto(parser, state, NON_TERMINAL_ARGUMENT, 90);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 91);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 63;
    state = 64;
    state = 65;
    state = 66;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 92);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 67;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 93);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 68;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 94);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 69;
    state = 70;
    state = 71;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 95);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 72;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 96);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 73;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 97);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 74;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 98);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 75;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 99);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 76;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 100);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 77;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 101);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 78;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 102);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 79;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 103);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 80;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 104);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 81;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 105);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 82;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 106);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 83;
    state = 84;
    state = 85;
    state = 86;
    state = 87;
    state = 88;
    state = 89;
    state = 90;
    state = 91;
    state = 92;
    state = 93;
    state = 94;
    state = 95;
    state = 96;
    state = 97;
    state = 98;
    state = 99;
    state = 100;
    state = 101;
    state = 102;
    state = 103;
    state = 104;
    state = 105;
    state = 106;
    state = 107;
    state = 108;
    state = 109;
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_ARGUMENTS, 112);
    set_parser_goto(parser, state, NON_TERMINAL_ARGUMENT, 90);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 91);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 110;
    state = 111;
    state = 112;
    state = 113;
    set_parser_goto(parser, state, NON_TERMINAL_BODY, 115);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENTS, 21);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENT, 22);
    set_parser_goto(parser, state, NON_TERMINAL_GETCHAR, 29);
    set_parser_goto(parser, state, NON_TERMINAL_PUTCHAR, 30);
    set_parser_goto(parser, state, NON_TERMINAL_DECLARATION, 24);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 32);
    set_parser_goto(parser, state, NON_TERMINAL_ASSIGNMENT, 23);
    set_parser_goto(parser, state, NON_TERMINAL_RETURN, 25);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 26);
    set_parser_goto(parser, state, NON_TERMINAL_WHILE_LOOP, 27);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 28);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 114;
    set_parser_goto(parser, state, NON_TERMINAL_BODY, 116);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENTS, 21);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENT, 22);
    set_parser_goto(parser, state, NON_TERMINAL_GETCHAR, 29);
    set_parser_goto(parser, state, NON_TERMINAL_PUTCHAR, 30);
    set_parser_goto(parser, state, NON_TERMINAL_DECLARATION, 24);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 32);
    set_parser_goto(parser, state, NON_TERMINAL_ASSIGNMENT, 23);
    set_parser_goto(parser, state, NON_TERMINAL_RETURN, 25);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 26);
    set_parser_goto(parser, state, NON_TERMINAL_WHILE_LOOP, 27);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 28);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 115;
    state = 116;
    state = 117;
    set_parser_goto(parser, state, NON_TERMINAL_ELSE_IF_OR_ELSE, 119);
    state = 118;
    state = 119;
    state = 120;
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 121);
    state = 121;
    state = 122;
    set_parser_goto(parser, state, NON_TERMINAL_BODY, 123);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENTS, 21);
    set_parser_goto(parser, state, NON_TERMINAL_STATEMENT, 22);
    set_parser_goto(parser, state, NON_TERMINAL_GETCHAR, 29);
    set_parser_goto(parser, state, NON_TERMINAL_PUTCHAR, 30);
    set_parser_goto(parser, state, NON_TERMINAL_DECLARATION, 24);
    set_parser_goto(parser, state, NON_TERMINAL_TYPE, 32);
    set_parser_goto(parser, state, NON_TERMINAL_ASSIGNMENT, 23);
    set_parser_goto(parser, state, NON_TERMINAL_RETURN, 25);
    set_parser_goto(parser, state, NON_TERMINAL_FUNCTION_CALL, 45);
    set_parser_goto(parser, state, NON_TERMINAL_IF_STATEMENT, 26);
    set_parser_goto(parser, state, NON_TERMINAL_WHILE_LOOP, 27);
    set_parser_goto(parser, state, NON_TERMINAL_EXPRESSION, 28);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_OR_TERM, 36);
    set_parser_goto(parser, state, NON_TERMINAL_LOGICAL_AND_TERM, 39);
    set_parser_goto(parser, state, NON_TERMINAL_RELATIONAL_TERM, 40);
    set_parser_goto(parser, state, NON_TERMINAL_ADDITIVE_TERM, 41);
    set_parser_goto(parser, state, NON_TERMINAL_MULTIPLICATIVE_TERM, 42);
    set_parser_goto(parser, state, NON_TERMINAL_FACTOR, 43);
    set_parser_goto(parser, state, NON_TERMINAL_LITERAL, 46);
    state = 123;
    state = 124;

}

void init_Production_Rules(Parser* parser){
    // intiating the parser production rules array
    int i = 0;

    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_THE_PROGRAM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_PROGRAM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FUNCTIONS, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FUNCTIONS, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FUNCTION, 8};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FUNCTION, 7};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_PARAMETERS, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_PARAMETERS, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_PARAMETER, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_BODY, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENTS, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENTS, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_STATEMENT, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_GETCHAR, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_PUTCHAR, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_DECLARATION, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_TYPE, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_TYPE, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_TYPE, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ASSIGNMENT, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RETURN, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RETURN, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FUNCTION_CALL, 4};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FUNCTION_CALL, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ARGUMENTS, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ARGUMENTS, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ARGUMENT, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_IF_STATEMENT, 8};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_IF_STATEMENT, 7};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ELSE_IF_OR_ELSE, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ELSE_IF_OR_ELSE, 4};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_WHILE_LOOP, 7};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_EXPRESSION, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_LOGICAL_OR_TERM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_LOGICAL_OR_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_LOGICAL_AND_TERM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_LOGICAL_AND_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_RELATIONAL_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ADDITIVE_TERM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ADDITIVE_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_ADDITIVE_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_MULTIPLICATIVE_TERM, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_MULTIPLICATIVE_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_MULTIPLICATIVE_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_MULTIPLICATIVE_TERM, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FACTOR, 3};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FACTOR, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FACTOR, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FACTOR, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FACTOR, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_FACTOR, 2};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_LITERAL, 1};
    parser->Production_Rules[i++] = (Production_Rule){NON_TERMINAL_LITERAL, 1};

}

